### ISSUE TITLE
Right-clicking on Python Project's Root causes a java.util.NoSuchElementException

### ISSUE THREAD

**Issue by emi-tech** [markiewb/nb-git-open-in-external-repoviewer#30]
I just performed a Plug-ins update and...

Right-clicking on Python Project's Root causes a java.util.NoSuchElementException shown below.
(No context menu appears on project root but sub tiers do show a context menu without issue)

This issue does not occur when context obtaining context menu of Java based projects.
Deactivated this Plugin and this issue does not manifest itself.
 
Plugin Version: 1.4.0.1

Nebeatns/JRE:
Product Version: NetBeans IDE 8.0.2 (Build 201411181905)
Updates: NetBeans IDE is updated to version NetBeans 8.0.2 Patch 2
Java: 1.8.0_60; Java HotSpot(TM) 64-Bit Server VM 25.60-b23
Runtime: Java(TM) SE Runtime Environment 1.8.0_60-b27
System: Windows 7 version 6.1 running on amd64; Cp1252; en_US (nb)

![untitled](https://cloud.githubusercontent.com/assets/3323215/10165930/9e56fae2-668f-11e5-8f70-1fb74076eaac.png)

java.util.NoSuchElementException
	at java.util.ArrayList$Itr.next(ArrayList.java:854)
	at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1042)
	at de.markiewb.netbeans.plugin.git.openinexternalviewer.actions.AbstractRepositoryPopupAction.detectRepositoryStrategy(AbstractRepositoryPopupAction.java:101)
	at de.markiewb.netbeans.plugin.git.openinexternalviewer.actions.AbstractRepositoryPopupAction.getPopupPresenter(AbstractRepositoryPopupAction.java:63)
	at org.openide.util.Utilities.actionsToPopup(Utilities.java:2842)
	at org.openide.util.Utilities.actionsToPopup(Utilities.java:2928)
	at org.openide.explorer.view.TreeView.createPopup(TreeView.java:1058)
	at org.openide.explorer.view.TreeView$PopupAdapter.showPopup(TreeView.java:1555)
	at org.openide.awt.MouseUtils$PopupMouseAdapter.maybePopup(MouseUtils.java:189)
	at org.openide.awt.MouseUtils$PopupMouseAdapter.mouseReleased(MouseUtils.java:184)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by markiewb** [comment]
Thanks Robert. I will fix it ASAP. In the meantime please disable the
plugin to continue working!

With kind regards, markiewb

2015-09-29 15:59 GMT+02:00 Robert Heusser <notifications@github.com>:

**Comment by markiewb** [comment]
Fixed in 1.4.0.2
